---
- name: dns for coder
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ username }}-code.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
    type: A
    overwrite: true
    value: "{{ ansible_host }}"
  delegate_to: localhost
  register: route53_status
  when: workshop_type is defined

- name: Download code-server 3 rpm
  get_url:
    url: https://github.com/cdr/code-server/releases/download/v3.10.2/code-server-3.10.2-amd64.rpm
    dest: /tmp/code-server.rpm
    mode: '0440'

- name: install code-server 3 rpm from local rpm and certbot
  dnf:
    name:
      - /tmp/code-server.rpm
      - certbot
    state: present
    disable_gpg_check: true

- name: Apply our systemd service file (instead of RPM file)
  template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service
    owner: "{{username}}"
    group: wheel
    mode: '0744'

    # source: https://vscode.readthedocs.io/en/latest/getstarted/settings/
- name: ensure custom facts directory exists
  file:
    path: "/home/{{ username }}/.local/share/code-server/User/"
    recurse: true
    state: directory
    owner: "{{ username }}"

- name: apply code server defaults
  template:
    src: settings.json
    dest: "/home/{{ username }}/.local/share/code-server/User/settings.json"
    owner: "{{ username }}"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/code-server/extensions/
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Download files for vscode
  get_url:
    url: "{{ item }}"
    dest: /home/{{ username }}/.local/share/code-server/extensions/
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - https://github.com/ansible/workshops/raw/devel/files/bierner.markdown-preview-github-styles-0.1.6.vsix
    - https://github.com/ansible/workshops/raw/devel/files/hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
    - https://github.com/ansible/workshops/raw/devel/files/vscoss.vscode-ansible-0.5.2.vsix

- name: install ansible and markdown extensions
  become_user: "{{ username }}"
  command: "/bin/code-server --install-extension /home/{{ username }}/.local/share/code-server/extensions/{{ item }}"
  loop:
    - bierner.markdown-preview-github-styles-0.1.6.vsix
    - hnw.vscode-auto-open-markdown-preview-0.0.4.vsix
    - vscoss.vscode-ansible-0.5.2.vsix
  ignore_errors: true
  register: install_extension
  until: install_extension is not failed
  retries: 5

- name: daemon-reload, enable and start code-server
  systemd:
    name: code-server
    enabled: true
    state: started
    daemon_reload: true

- name: "install nginx"
  dnf:
    name: ['nginx']
    state: latest

- name: delete all commented lines nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: absent
    regexp: '#.*'

# if we do not have a cert we will try to work anyway
- name: issue cert
  shell: certbot certonly --no-bootstrap --standalone -d {{ username }}-code.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }} --email ansible-network@redhat.com --noninteractive --agree-tos
  register: issue_cert
  until: issue_cert is not failed
  retries: 5
  ignore_errors: true
  when: workshop_type is defined

- name: update nginx configuration to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx.conf') }}"
    dest: /etc/nginx/nginx.conf
    insertafter: "http {"
  when: workshop_type is defined

- name: instruqt - update nginx configuration to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx_instruqt.conf') }}"
    dest: /etc/nginx/nginx.conf
    insertafter: "location /"
  when: workshop_type is not defined

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: "enable nginx"
  service:
    name: nginx
    enabled: yes


